package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CheckListAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListAllPropertiesEquals(CheckList expected, CheckList actual) {
        assertCheckListAutoGeneratedPropertiesEquals(expected, actual);
        assertCheckListAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListAllUpdatablePropertiesEquals(CheckList expected, CheckList actual) {
        assertCheckListUpdatableFieldsEquals(expected, actual);
        assertCheckListUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListAutoGeneratedPropertiesEquals(CheckList expected, CheckList actual) {
        assertThat(actual)
            .as("Verify CheckList auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListUpdatableFieldsEquals(CheckList expected, CheckList actual) {
        assertThat(actual)
            .as("Verify CheckList relevant properties")
            .satisfies(a -> assertThat(a.getCheckListId()).as("check checkListId").isEqualTo(expected.getCheckListId()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListUpdatableRelationshipsEquals(CheckList expected, CheckList actual) {
        // empty method
    }
}
