package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LabelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabelAllPropertiesEquals(Label expected, Label actual) {
        assertLabelAutoGeneratedPropertiesEquals(expected, actual);
        assertLabelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabelAllUpdatablePropertiesEquals(Label expected, Label actual) {
        assertLabelUpdatableFieldsEquals(expected, actual);
        assertLabelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabelAutoGeneratedPropertiesEquals(Label expected, Label actual) {
        assertThat(actual)
            .as("Verify Label auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabelUpdatableFieldsEquals(Label expected, Label actual) {
        assertThat(actual)
            .as("Verify Label relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getColor()).as("check color").isEqualTo(expected.getColor()))
            .satisfies(a -> assertThat(a.getTrelloId()).as("check trelloId").isEqualTo(expected.getTrelloId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabelUpdatableRelationshipsEquals(Label expected, Label actual) {
        assertThat(actual)
            .as("Verify Label relationships")
            .satisfies(a -> assertThat(a.getCards()).as("check cards").isEqualTo(expected.getCards()));
    }
}
