package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WorkspaceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkspaceAllPropertiesEquals(Workspace expected, Workspace actual) {
        assertWorkspaceAutoGeneratedPropertiesEquals(expected, actual);
        assertWorkspaceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkspaceAllUpdatablePropertiesEquals(Workspace expected, Workspace actual) {
        assertWorkspaceUpdatableFieldsEquals(expected, actual);
        assertWorkspaceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkspaceAutoGeneratedPropertiesEquals(Workspace expected, Workspace actual) {
        assertThat(actual)
            .as("Verify Workspace auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkspaceUpdatableFieldsEquals(Workspace expected, Workspace actual) {
        assertThat(actual)
            .as("Verify Workspace relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getTrelloId()).as("check trelloId").isEqualTo(expected.getTrelloId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkspaceUpdatableRelationshipsEquals(Workspace expected, Workspace actual) {
        // empty method
    }
}
